/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package syk.drone.mavlink.enums;

/** 
* 
*/
public class CAMERA_STATUS_TYPES {
   public static final int CAMERA_STATUS_TYPE_HEARTBEAT = 0; /* JpegUtil heartbeat, announce camera component ID at 1Hz. | */
   public static final int CAMERA_STATUS_TYPE_TRIGGER = 1; /* JpegUtil image triggered. | */
   public static final int CAMERA_STATUS_TYPE_DISCONNECT = 2; /* JpegUtil connection lost. | */
   public static final int CAMERA_STATUS_TYPE_ERROR = 3; /* JpegUtil unknown error. | */
   public static final int CAMERA_STATUS_TYPE_LOWBATT = 4; /* JpegUtil battery low. Parameter p1 shows reported voltage. | */
   public static final int CAMERA_STATUS_TYPE_LOWSTORE = 5; /* JpegUtil storage low. Parameter p1 shows reported shots remaining. | */
   public static final int CAMERA_STATUS_TYPE_LOWSTOREV = 6; /* JpegUtil storage low. Parameter p1 shows reported video minutes remaining. | */
   public static final int CAMERA_STATUS_TYPES_ENUM_END = 7; /*  | */
}
            